name: plain_auth
description: "Plain Potato authentication package."
version: 0.0.1
publish_to: none
#homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  facebook_auth_desktop:
    git:
      url: git@github.com:potatojoayo/flutter-facebook-auth.git
      path: facebook_auth_desktop
  firebase_auth: ^4.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth:
    git:
      url: git@github.com:potatojoayo/flutter-facebook-auth.git
      path: facebook_auth
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.3
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.5

flutter:
