name: plain_auth
description: "Plain Potato authentication package."
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.4
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.5

flutter:
